---
title: "Statistics and R - Week 2"
subtitle: "HarvardX PH525.1x: Data Analysis for Life Sciences 1"
output: pdf_document
---
# Mathematical notation

Textbook code can be found [here](https://github.com/genomicsclass/labs/blob/master/intro/math_notation.Rmd) or downloaded:
```{r, eval=FALSE, tidy=TRUE}
library(downloader)
url="https://github.com/genomicsclass/labs/raw/master/intro/math_notation.Rmd"
filename=basename(url)
download(url,filename)
```

# Week 2

# Inference, Random Variables, & Probability Distributions

Textbook code can be found [here](https://github.com/genomicsclass/labs/blob/master/inference/random_variables.Rmd) or downloaded:
```{r, eval=FALSE, tidy=TRUE}
library(downloader)
url="https://github.com/genomicsclass/labs/raw/master/inference/random_variables.Rmd"
filename=basename(url)
download(url,filename)
```

## Random Variables

```{r, echo=FALSE}
library(downloader)
dir <- "https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/"
filename <- "femaleControlsPopulation.csv"
url <- paste0(dir, filename)
##check if file exists and if it does not, download it:
if (!file.exists(filename)) download(url,destfile=filename)
```

```{r}
population <- read.csv("femaleControlsPopulation.csv")
##use unlist to turn it into a numeric vector
population <- unlist(population) 
```

## The Null Hypothesis & Null Distribution





# Central Limit Theorem
